name: "Start agent"
stages:
    boot:
    - if: '[ ! -f "/run/cos/recovery_mode" ]'
      commands:
       - systemctl start c3os-agent
       - systemctl enable c3os-agent
    initramfs:
    - if: '[ ! -f "/run/cos/recovery_mode" ]'
      commands:
       - systemctl enable c3os-agent
    - name: "openRC setup"
    - if: '[ ! -f "/run/cos/recovery_mode" ] && [ -e "/sbin/openrc" ]'
      commands:
      - |
        mkdir -p /etc/runlevels/default
        for SVC in c3os-agent
        do
            ln -sf /etc/init.d/$SVC /etc/runlevels/default/$SVC
        done